### ISSUE TITLE
 Not any data file has been found in '/tmp' directory

### ISSUE THREAD

**Issue by Jeoffreybauvin** [ssenart/PyGazpar#25]
Hi,

I'm using the latest pygazpar version and since, it seems to be broken : 

Here is my script : https://github.com/Jeoffreybauvin/pygazpar_to_influxdb

Here is the error : pygazpar.webdriverwrapper (WARNING): Not any data file has been found in '/tmp' directory

Full log :

```
pygazpar.webdriverwrapper (DEBUG): find_element_by_xpath('//button[contains(.,'Télécharger')]'): Download button...
selenium.webdriver.remote.remote_connection (DEBUG): POST http://127.0.0.1:46769/session/46887c7d-0a20-46c7-9dc1-f0309fa4b05e/element {"using": "xpath", "value": "//button[contains(.,'T\u00e9l\u00e9charger')]"}
urllib3.connectionpool (DEBUG): http://127.0.0.1:46769 "POST /session/46887c7d-0a20-46c7-9dc1-f0309fa4b05e/element HTTP/1.1" 200 88
selenium.webdriver.remote.remote_connection (DEBUG): Finished Request
pygazpar.webdriverwrapper (DEBUG): find_element_by_xpath('//button[contains(.,'Télécharger')]'): Download button -> Ok
pygazpar.webelementwrapper (DEBUG): click(): Download button...
selenium.webdriver.remote.remote_connection (DEBUG): POST http://127.0.0.1:46769/session/46887c7d-0a20-46c7-9dc1-f0309fa4b05e/element/e8b78b92-2ebe-4ada-97ad-5919606e311b/click {"id": "e8b78b92-2ebe-4ada-97ad-5919606e311b"}
urllib3.connectionpool (DEBUG): http://127.0.0.1:46769 "POST /session/46887c7d-0a20-46c7-9dc1-f0309fa4b05e/element/e8b78b92-2ebe-4ada-97ad-5919606e311b/click HTTP/1.1" 200 14
selenium.webdriver.remote.remote_connection (DEBUG): Finished Request
pygazpar.webelementwrapper (DEBUG): click() -> Ok
pygazpar.webdriverwrapper (WARNING): Not any data file has been found in '/tmp' directory
pygazpar.client (DEBUG): The data update terminates normally
pygazpar.webdriverwrapper (DEBUG): quit()...
selenium.webdriver.remote.remote_connection (DEBUG): DELETE http://127.0.0.1:46769/session/46887c7d-0a20-46c7-9dc1-f0309fa4b05e {}
urllib3.connectionpool (DEBUG): http://127.0.0.1:46769 "DELETE /session/46887c7d-0a20-46c7-9dc1-f0309fa4b05e HTTP/1.1" 200 14
selenium.webdriver.remote.remote_connection (DEBUG): Finished Request
pygazpar.webdriverwrapper (DEBUG): quit() -> Ok
root (DEBUG): End update pygazpar data
```

Is it any change I'm missing ?

Regards,

**Comment by ssenart** [comment]
Hi,

Since the new version, GrDF web site is very unstable... Some freeze, missing data, internal server error...

Furthermore, I see some random popup windows (privacy, new site presentation...) that may brake PyGazpar at any time.

The login is now guarded with a CAPTCHA : It is not yet efficient, but I expect it will prevent PyGazpar to work definitively in a near future.

For the moment, it works. I managed to load my data as before. But i'm afraid it won't last.

Regards,
Stephane

**Comment by ssenart** [comment]
Perhaps your issue is related to the new parameter lastNDays used to load only the last N days of data.

Did you miss it ?

**Comment by pbranly** [comment]
Hi,
Where should we define this parameter ?
Thanks
Philippe

**Comment by ssenart** [comment]
It is in the Client class constructor. It has a default value of 365 days. Do you use it directly ? Or through another component that do invoke that constructor ?

**Comment by Jeoffreybauvin** [comment]
Hello @ssenart ,

It seems to be ok with 1.0.2 :).
