### ISSUE TITLE
error selenium.common.exceptions.ElementClickInterceptedException: Message: Element <span class="ui-button-text ui-c"> is not clickable at point (1075,1035) because another element <img src="//img.tokywoky.com/groupcategories/602/tiny-second-minimized.png"> obscures it

### ISSUE THREAD

**Issue by laurentpoum** [ssenart/PyGazpar#3]
Looks like grdf added the « questions client » part just in front of the button...

![](https://img.tokywoky.com/groupcategories/602/tiny-second-minimized.png)

Any idea on how to solve this?

Just to give context, it’s on the download_button_element.click()

**Comment by ssenart** [comment]
Thanks, I did not realize that it comes from that bubble.

I will try to locate it and force click on its close button...

**Comment by laurentpoum** [comment]
Thanks,

I also have an improvement to propose for my domotic intégration (I modifier the file manually for it but a parameter would be nice), do you want me to open it as an issue or is there somewhere else for that ?

**Comment by ssenart** [comment]
I suggest to add a new parameter "lastNRows" that permit to control how many you would like. In your use case, il will be lastNRows=1. Is ok ?

**Comment by ssenart** [comment]
The new version 0.1.14 fixes the hide button issue (and other cases) and delivers the new parameter lastNRows.
Tests are fine in my environment. Let me know whether it is also ok in yours.

**Comment by laurentpoum** [comment]
Juste tested, works perfectly on my side too 

Thanks !
