### ISSUE TITLE
Erreur de lancement 

### ISSUE THREAD

**Issue by pbranly** [ssenart/PyGazpar#36]
Bonjour
J’ai cette erreur dans les logs: 

`
  File "/usr/local/lib/python3.9/dist-packages/pygazpar/client.py", line 57, in update

    self.__updateLiveMode()

  File "/usr/local/lib/python3.9/dist-packages/pygazpar/client.py", line 108, in __updateLiveMode

    startDate = endDate + datetime.timedelta(days=-self.__lastNDays)

TypeError: bad operand type for unary -: 'str' `
Merci d’avance 
Philippe

**Comment by ssenart** [comment]
Bonjour,

Comment appelles-tu le constructeur de la classe Client ? Quelle est la liste des paramètres ?

Attention, depuis la version 1.1.0, la liste des paramètres a changé, maintenant c'est:
```python
username: str, 
password: str, 
pceIdentifier: int, 
meterReadingFrequency: Frequency = DEFAULT_METER_READING_FREQUENCY, 
lastNDays: int = DEFAULT_LAST_N_DAYS, 
tmpDirectory: str = DEFAULT_TMP_DIRECTORY, 
testMode: bool = False
```
J'ai retiré ce qui était en rapport avec Selenium et rajouter pceIdentifier qui est le numéro PCE de ton compteur (visible sur le site GrDF).
Du coup, il est possible que ton erreur apparaisse car tu as conservé l'ancienne liste de paramètres.

Méa coupla, j'ai oublié de préciser ce changement dans la CHANGELOG.

Stéphane

**Comment by pbranly** [comment]
Merci.
Jutilise votre github pour ecrire les datas directement dans Influx
J'ai changé quelques lignes mais j'ai encore une erreur:
`client = pygazpar.Client(args.PYGAZPAR_LOGIN,
                         args.PYGAZPAR_PASSWORD,
                         args.PCE_IDENTIFIER,
                         'Frequency.DAILY',
                         30,
                         '/tmp')
`
l’erreur est: 
`root (DEBUG): Starting to update pygazpar data


pygazpar.client (DEBUG): Start updating the data...


pygazpar.client (ERROR): An unexpected error occured while updating the data


Traceback (most recent call last):


  File "/usr/local/lib/python3.9/dist-packages/pygazpar/client.py", line 110, in __updateLiveMode


    downloadUrl = DATA_URL.format(frequencies[self.__meterReadingFrequency], startDate.strftime(dateFormat), endDate.strftime(dateFormat), self.__pceIdentifier)


KeyError: 'Frequency.DAILY'


Traceback (most recent call last):


  File "/data/pygazpar_to_influxdb.py", line 62, in <module>


    client.update()


  File "/usr/local/lib/python3.9/dist-packages/pygazpar/client.py", line 57, in update


    self.__updateLiveMode()


  File "/usr/local/lib/python3.9/dist-packages/pygazpar/client.py", line 110, in __updateLiveMode


    downloadUrl = DATA_URL.format(frequencies[self.__meterReadingFrequency], startDate.strftime(dateFormat), endDate.strftime(dateFormat), self.__pceIdentifier)


KeyError: 'Frequency.DAILY'`

quelle est la syntaxe a utiliser pour entrer frequency.daily ?
merci d'avance
Philippe

**Comment by ssenart** [comment]
Bonjour,

C'est sans les quotes autour, et mettre pygazpar.Frequency.DAILY si la classe Frequency n'est pas importée. Tu peux regarder dans les sources de PyGazpar comment la commande est  appelée dans __main__.py: c est un exemple.

Stéphane

**Comment by pbranly** [comment]
merci ca fonctionne

bravo
Philippe

**Comment by pbranly** [comment]
par contre mon docker continue a importer firefox et geckodriver. je ne suis pas sur que cela vienne de mon code:

![2021-12-04_12-14](https://user-images.githubusercontent.com/22018509/144707392-9a1eaf20-a335-4b05-9d21-25043de5afeb.png)

**Comment by ssenart** [comment]
Cela vient de ton docker file qui t a permis de créer ton image et container.

**Comment by pbranly** [comment]
merci. j'ai effacé toute la configuration de mon docker. cela m'a permis de
pouvoir supprimer l'image geckodriver.
 la réinstallation du docker n'a plus reinstallé geckodriver
Philippe
ps: je ferme cet issue
