### ISSUE TITLE
NameError: name 'Frequency' is not defined

### ISSUE THREAD

**Issue by nicolas-r** [ssenart/PyGazpar#39]
Hello

When trying to use the sample code, I get

Traceback (most recent call last):
  File "C:\Users\nicol\Documents\dev\grdf\grdf-import.py", line 7, in <module>
    meterReadingFrequency=Frequency.DAILY,
NameError: name 'Frequency' is not defined

If I addthe line below, the error is gone
from pygazpar.enum import Frequency

Nicolas

**Comment by ssenart** [comment]
Fixed in 1.1.2
