### ISSUE TITLE
New problem with grdf website

### ISSUE THREAD

**Issue by patoche94** [ssenart/PyGazpar#4]
It seems a new problem occurs preventing pygazpar to work since a few days (probably a new « help » button on grdf web site that I do not remember existing before)
Any way to solve this ?
Thanks

**Comment by ssenart** [comment]
Hi,

Did you already update to version 0.1.14 ?

This version is still working fine. I have just double checked.

**Comment by patoche94** [comment]
Hi,
Sorry, I just realized my mistake : I’m indeed using the last pygazpar version but I just found a problem with JMQTT broker I’m using to transfer gazpar data to Jeedom 
Problem is fixed now and pygazpar is working fine
There is therefore no more issue
Thanks
