### ISSUE TITLE
la durée demandée ne fonctionne plus

### ISSUE THREAD

**Issue by pbranly** [ssenart/PyGazpar#43]
Bonjour,
a chaque fois que je tente de recuperer une plage de données (20j par exemple) le programme ne tente de recuperer que la donnée 20 jours avant uniquement.
y a t il un pb avec le procole gazpar ?
cdlt
Philippe

**Comment by ssenart** [comment]
Bonjour,
Depuis quand as-tu ce comportement ?
Stéphane

**Comment by ssenart** [comment]
En ce moment, le site GrDF affiche le message :

"Le téléchargement de vos données est temporairement indisponible. Veuillez nous excuser pour la gêne occasionnée."

Et en effet, cela ne fonctionne plus.

**Comment by pbranly** [comment]
Merci 
Je verrai demain si ça refonctionne 
Pour l'instant la demande de plage de dates ne donne rien sauf une tentative à la date de début de plage .
Mais c'est peut être avec mon programme !
Philippe

**Comment by pbranly** [comment]
Bonjour,
J'ai tenté en ligne de commande et cela ne fonctionne plus non plus:
nota par rapport a la doc j'ai fait
pip install pygazpar==1.1.2 sinon il installe la version 1.02

pygazpar -u 'xxxx@yy.fr' -p 'tyuiop' -c '0123456789xxx' -d 30 -t /tmp > test.txt

la commande fonctionne mais le fichier généré ne comporte que:
[]
Amitiés 
Philippe

**Comment by ssenart** [comment]
Bonjour,

Le téléchargement des données depuis le site GrDF ne fonctionne plus depuis hier. Du coup, PyGazpar ne fonctionne plus, puisqu'il utilise cette fonction de téléchargement.

Stéphane

**Comment by pbranly** [comment]
Oui ça doit être cela , ton protocole n’est actuellement plus supporté .
Par contre, je récupère bien les valeurs avec d’autres systèmes qui je pense n’utilisent pas le pdl. 
Ces systèmes doivent continuer à emuler la page web de GRDF
Phil

**Comment by ssenart** [comment]
Il semble que le téléchargement refonctionne de temps en temps. Par contre, le nom du fichier téléchargé a changé. Il a été renommé de Donnees_informatives_PCE_{dateDebut}_{dateFin}.xlsx en Donnees_informatives_{NumeroPCE}_{dateDebut}_{dateFin}.xlsx.

Je dois adapter le code...

**Comment by pbranly** [comment]
la version 1.1.4 fonctionne
Merci
Philippe
