### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by pbranly** [ssenart/PyGazpar#57]
Hi
I use your engine version 1.1.6. I had to change my password in the GRDF site .
I have verified that my new password works
I can't login anymore and get those errors:

Exception: LOGIN_INVALID_ATTEMPTS
Traceback (most recent call last):
  File "/data/./pygazpar_to_influxdb.py", line 55, in <module>
    client.update()
  File "/usr/local/lib/python3.9/site-packages/pygazpar/client.py", line 54, in update
    self.__updateLiveMode()
  File "/usr/local/lib/python3.9/site-packages/pygazpar/client.py", line 96, in __updateLiveMode
    self.__login(session)
  File "/usr/local/lib/python3.9/site-packages/pygazpar/client.py", line 160, in __login
    raise Exception(loginData["error"])
Exception: LOGIN_INVALID_ATTEMPTS

Phil

**Comment by pbranly** [comment]
Fix: no use of special character

**Comment by ssenart** [comment]
Hello,

In your password, do you have special characters (such as %, ?, @...). It may cause that behaviour.

**Comment by pbranly** [comment]
Yes sorry GRDF asks me to create a password with special character . This was the reason . It is modified now and it works
Phil

**Comment by ssenart** [comment]
What was the character that caused the error ? Perhaps, I have to encode the password before submitting it...

**Comment by pbranly** [comment]
A comma at the end : xxxxxxxx, ! But perhaps there is the same issue for others
Phil

**Comment by tikismoke** [comment]
Was the same for me, removing such char at the end solve the issue.
