### ISSUE TITLE
Captcha failed issue

### ISSUE THREAD

**Issue by martindaniel4** [ssenart/PyGazpar#64]
Can't retrieve data from my Gazpar account. I get a: 

```python 
  File "/Users/martindaniel/opt/miniconda3/lib/python3.9/site-packages/pygazpar/datasource.py", line 92, in _login
    raise Exception(loginData["error"])
Exception: CAPTCHA_FAIL
```

**Comment by ssenart** [comment]
Same issue with my account.

I can't even logged in the GrDF web site.

**Comment by martindaniel4** [comment]
This one will be hard to bypass :/ 

![Capture d’écran 2023-01-16 à 13 54 58](https://user-images.githubusercontent.com/695006/212683083-cec21500-6900-4a5a-8d14-b7bed4e548e2.png)

**Comment by Jeoffreybauvin** [comment]
Login on GRDF website is working again. Any plan to bypass this reCaptcha ? :(

**Comment by ssenart** [comment]
I don't know how to bypass ?

There are some online services that do that but they are not free...

**Comment by Jeoffreybauvin** [comment]
@ssenart  I tried https://github.com/xHossein/PyPasser, but no luck.

**Comment by Marc-AntoineA** [comment]
I used Pygazpar through a cron job to request and add data to my influxdb database.

I don’t believe that bypassing recaptcha will be easy so I am okay to complete the recaptcha once a day, when I want to see my data. But I don’t want to manually download everything by hand.

Do you have any idea of how I could upgrade Pygazpar to manually complete recaptcha?

For now, I try to create a Firefox extension:
* I complete the login page myself with prefilled values ;
* data is automatically downloaded and uploaded to InfluxDb

Source code will be there: https://framagit.org/Marc-AntoineA/firegaz

**Comment by mdeweerd** [comment]
Pour info, une alternative est en cours de mise au point.
Pour les évolutions suivre [fil de discussion sur hacf.fr](https://forum.hacf.fr/t/gazpar-grdf-ko-suite-exigence-captcha/20004?u=le_top).

Cela pourra être ajusté pour appelé dans un script ou ne produire que le json localement.
