### ISSUE TITLE
Excel file not written

### ISSUE THREAD

**Issue by Olivier6767** [ssenart/PyGazpar#68]
Script Version : 1.2.2 - Ubuntu Focal - AMD64

I'm trying this script to get the data from the GRDF web site downloaded in Excel format.
The script runs fine, the output is displayed, the log file is generated in the temporary folder but the Excel file is not generated...

Here is the command line: 
`pygazpar -u '<user>' -p '<password>' -c 'PCE' -t '/tmp' -d 365 --datasource 'excel'`

Here are the last lines of the log file:
`2024-06-01 15:18:15,670 DEBUG [urllib3.connectionpool] Starting new HTTPS connection (1): monespace.grdf.fr:443`
`2024-06-01 15:18:16,561 DEBUG [urllib3.connectionpool] https://monespace.grdf.fr:443 "GET /api/e-conso/pce/consommation/informatives/telecharger?dateDebut=2023-06-02&dateFin=2024-06-01&frequence=Journalier&pceList%5B%5D=<PCE> HTTP/1.1" 200 48592`
`2024-06-01 15:18:16,579 DEBUG [pygazpar.excelparser] Loading Excel data file '/tmp/Donnees_informatives_<PCE>_2023-06-02_2024-06-01_665b1f97b279d.xlsx'...`
`2024-06-01 15:18:16,619 DEBUG [pygazpar.excelparser] Daily data read successfully between row #10 and row #371`
`2024-06-01 15:18:16,620 DEBUG [pygazpar.datasource] The data update terminates normally`
`2024-06-01 15:18:16,620 DEBUG [pygazpar.client] The data load terminates normally`

Am'I missing something?

**Comment by ssenart** [comment]
hello, the excel file is only temporary and removed at the of the command, once it has been parsed successfully.

**Comment by Olivier6767** [comment]
Thanks for the clarification.
It would be nice to have an option to keep it, as in my case I use it to upload the data to Domoticz.
